### PR TITLE
Tasks/#1 setup helm chart repo

### PR DESCRIPTION
**Pull request by phucvdb**
Please do the following before you run my scripts in travis-ci:
1. Setup your gcs for both of stable and incubator repository that should follow the guide
https://github.com/helm/helm/blob/master/docs/chart_repository.md#hosting-chart-repositories

2. Create a service account in Google IAM and get the credential of gcs and save it to json file as name "credential.json". this service account should have the role as "Storage Object Admin"
https://cloud.google.com/storage/docs/authentication#generating-a-private-key

3. encrypt your "credential.json" by follow 
https://docs.travis-ci.com/user/encrypting-files/

4. Copy the output with openssl and using it later.

5. Create the slack secure channel with travis and save the secret key

6. update the your openssl command and secret key to file .travis.yaml

Finally, you can commit and push your code to github to test travis-ci and check your helm chart repository

connect #1

### CODE REVIEW

**Comment by hieptranquoc** [comment]
@phucvdb you need merge into 1 commit!

**Comment by hieptranquoc** [comment]
@phucvdb you should use the commit message "@ #number | message"! Otherwise, MR HoatLe will criticize it!

**Comment by phucvdb** [comment]
@hieptranquoc Thanks you. I will close this PR and make another after I update my git commit

**Comment by hieptranquoc** [comment]
@phucvdb You can use `git squash` to merge many commits into 1 :D

**Pull request closed without merging**
